### ISSUE TITLE
Attached images

### ISSUE THREAD

**Issue by garmoshka-mo** [garmoshka-mo/mo-wire#1]
![screen shot 2015-10-19 at 12 47 52](https://cloud.githubusercontent.com/assets/2452269/10574962/fc3a972c-7661-11e5-9bfd-4eee7bce9a6b.jpg)

**Comment by garmoshka-mo** [comment]
![screen shot 2015-10-19 at 12 47 52](https://cloud.githubusercontent.com/assets/2452269/10575034/772343bc-7662-11e5-9523-174ce6e9a792.jpg)

**Comment by FlorianWendelborn** [comment]
May I ask what this is supposed to mean?

**Comment by garmoshka-mo** [comment]
It is attempt to "visualize" metaphor of "wiring" in code.
Looks confusing?

**Comment by FlorianWendelborn** [comment]
No, but it looks like the best syntax highlighting plugin solution for this wire-approach ever.

**Comment by garmoshka-mo** [comment]
ah, the wire on picture - is just image which i added in photoshop, 
it is not something, what drawn automatically in editor
